#!/usr/bin/env bun
// Copyright 2026 Yohan Pierre
// SPDX-License-Identifier: Apache-2.0
//
// Codegen schéma — source de vérité unique : schema/v2.json.
// Produit :
//   - crates/n2b-types/src/schema.rs       via `cargo typify`
//   - packages/n2b-types/src/index.ts      via `json-schema-to-typescript --unreachableDefinitions`
//
// Les deux fichiers sont commités. La CI échoue si drift (mode --check).
//
// Usage :
//   bun run scripts/generate-schema-types.ts          # régénère
//   bun run scripts/generate-schema-types.ts --check  # exit 1 si drift

import { $ } from "bun";
import { existsSync } from "node:fs";
import { resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "..");
const SCHEMA = `${REPO_ROOT}/schema/v2.json`;
const RUST_OUT = `${REPO_ROOT}/crates/n2b-types/src/schema.rs`;
const TS_OUT = `${REPO_ROOT}/packages/n2b-types/src/index.ts`;

const BANNER_RS = `// @generated — DO NOT EDIT MANUALLY.
// Regenerate with: bun run scripts/generate-schema-types.ts
// Source of truth: schema/v2.json

`;

const BANNER_TS = `// @generated — DO NOT EDIT MANUALLY.
// Regenerate with: bun run scripts/generate-schema-types.ts
// Source of truth: schema/v2.json

`;

const HEADER_TS_REGEX =
	/^\/\* eslint-disable \*\/\n\/\*\*\n \* This file was automatically generated by json-schema-to-typescript\.\n \* DO NOT MODIFY IT BY HAND\. Instead, modify the source JSONSchema file,\n \* and run json-schema-to-typescript to regenerate this file\.\n \*\/\n/;

async function generateRust(): Promise<string> {
	const tmp = `/tmp/n2b-schema-${process.pid}.rs`;
	const result = await $`cargo typify -o ${tmp} ${SCHEMA}`.quiet();
	if (result.exitCode !== 0) {
		throw new Error(`cargo typify failed: ${result.stderr.toString()}`);
	}
	const body = await Bun.file(tmp).text();
	await Bun.file(tmp).delete();
	return BANNER_RS + body;
}

async function generateTs(): Promise<string> {
	const result =
		await $`bunx --bun json-schema-to-typescript --unreachableDefinitions ${SCHEMA}`.quiet();
	if (result.exitCode !== 0) {
		throw new Error(
			`json-schema-to-typescript failed: ${result.stderr.toString()}`,
		);
	}
	const out = result.stdout.toString();
	if (!HEADER_TS_REGEX.test(out)) {
		throw new Error(
			"json-schema-to-typescript output header changed; update HEADER_TS_REGEX",
		);
	}
	return BANNER_TS + out.replace(HEADER_TS_REGEX, "").replace(/^\n+/, "");
}

async function main(): Promise<void> {
	if (!existsSync(SCHEMA)) {
		console.error(`schema not found: ${SCHEMA}`);
		process.exit(1);
	}

	const check = process.argv.includes("--check");
	const [rust, ts] = await Promise.all([generateRust(), generateTs()]);

	if (check) {
		const [rustCommitted, tsCommitted] = await Promise.all([
			Bun.file(RUST_OUT).text(),
			Bun.file(TS_OUT).text(),
		]);
		let drift = false;
		if (rust !== rustCommitted) {
			console.error(`drift: ${RUST_OUT}`);
			drift = true;
		}
		if (ts !== tsCommitted) {
			console.error(`drift: ${TS_OUT}`);
			drift = true;
		}
		if (drift) {
			console.error(
				"\nRun `bun run codegen:schema` and commit the regenerated files.",
			);
			process.exit(1);
		}
		console.log("codegen:schema:check OK — no drift");
		return;
	}

	await Promise.all([Bun.write(RUST_OUT, rust), Bun.write(TS_OUT, ts)]);
	console.log(`wrote ${RUST_OUT}`);
	console.log(`wrote ${TS_OUT}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
